// sample.js — 内置示例书库（公版 / 公版节选简写），首次启动自动预载
// 难度阶梯：Grimm 简写（入门）→ Aesop（B1）→ O. Henry 节选（B1-B2）

const GRIMM = {
  title: "Grimm's Fairy Tales（简写版）",
  author: 'Brothers Grimm · 简写',
  chaptersRaw: [
    {
      title: 'The Frog Prince',
      text: [
        'In old times, when wishing still helped, there lived a king whose daughters were all beautiful. The youngest was so lovely that the sun itself, which had seen so much, wondered every time it shone upon her face.',
        'Close to the king\'s castle lay a great dark forest. Under an old lime-tree in the forest was a well. When the day was very warm, the princess sat down by the edge of the cool well. To pass the time, she would throw a golden ball up in the air and catch it as it fell.',
        'One day, the ball flew too high. The princess stretched out her hand, but she could not catch it. The golden ball fell into the water with a splash. The well was so deep that no one could see the bottom.',
        'The princess began to cry. "Alas," she said, "if I could only get my ball again, I would give anything for it."',
        'Then a voice called out: "What is the matter, princess? Your tears would move even a stone." She looked around, and saw a frog stretching its thick, ugly head out of the water.',
        '"Ah, old water-splasher, is it you?" said she. "I am crying for my golden ball, which has fallen into the well."',
        '"I can bring your ball back," said the frog. "But what will you give me if I do?"',
        '"Whatever you like, dear frog," said the princess. "My clothes, my pearls, even the golden crown I wear."',
        'The frog answered: "I do not care for your pearls or your crown. But if you will love me, and let me be your companion and play-fellow — sit by you at your little table, eat from your little golden plate, and sleep in your little bed — then I will bring your ball back to you."',
        '"Yes, yes," said the princess. "I promise it all, if you will only bring my ball back." She thought to herself: "How silly the frog talks! He can only sit in the water and croak. He can never be a companion to a human being."',
        'As soon as the frog heard her promise, he put his head under the water and sank down. In a short time he came swimming up again, with the ball in his mouth, and threw it on the grass.',
        'The princess was filled with joy when she saw her beautiful ball again. She picked it up and ran away. "Wait, wait!" called the frog. "Take me with you. I cannot run as fast as you." But it was no use. She ran home, and soon forgot the poor frog, who had to jump back into his well.',
        'The next day, as the princess sat at dinner with the king and all the court, something came creeping up the marble steps: splish, splash! When it reached the top, it knocked at the door and cried: "Youngest king\'s daughter, open to me."',
        'She ran to see who was outside. When she opened the door, there sat the frog. In fright she slammed the door and sat down again, her heart beating very fast.',
        'The king saw that her heart was beating hard, and said: "My child, what are you afraid of? Is there a giant outside who wants to carry you away?"',
        '"Ah no," replied she. "It is a disgusting frog. Yesterday, when I was playing by the well, my golden ball fell into the water. And because I cried so much, the frog brought it back. He made me promise he should be my companion. I never thought he could leave his water. But now he is outside, and wants to come in."',
        'Then the frog knocked again and cried: "King\'s daughter, king\'s daughter, open the door. Do you not remember what you said by the cool water? King\'s daughter, king\'s daughter, open the door."',
        'Then said the king: "That which you have promised, you must keep. Go and let him in."',
        'So she opened the door, and the frog hopped in, step by step, until he reached her chair. There he sat and cried: "Lift me up beside you." She delayed until the king commanded her to do it. Once the frog was on the chair, he wanted to be on the table. When he was on the table, he said: "Now push your little golden plate nearer to me, so that we may eat together."',
        'She did as he asked, but it was easy to see that she did not like it. The frog enjoyed his dinner, but every bite she took stuck in her throat.',
        'At last the frog said: "I have eaten enough, and I am tired. Carry me upstairs, and put me into your little bed." Then the princess began to weep. She was afraid of the cold frog, whom she did not dare to touch, and who was now to sleep in her pretty clean little bed.',
        'But the king said: "He who helped you when you were in trouble must not be despised now." So she took the frog with two fingers, carried him upstairs, and put him in a corner. But when she lay in bed, he crept up to her and said: "I am tired, I want to sleep as well as you. Lift me up, or I will tell your father."',
        'Then she was terribly angry. She picked up the frog with all her strength, and threw him against the wall. "Now you will have your rest, you disgusting frog!"',
        'But when he fell down, he was no longer a frog. He was a king\'s son with kind and beautiful eyes. He told her that he had been cursed by a wicked witch, and no one but she could free him from the well. He asked her to keep him as her companion and friend. They would go together into his kingdom and be married.',
        'Then sleep came to her tired eyes. The next morning, a splendid carriage arrived with eight white horses carrying white ostrich feathers, and golden chains. Behind stood the young king\'s faithful servant Henry. When his master had been turned into a frog, Henry had put three iron bands around his heart, so that it might not burst with grief and sorrow.',
        'The king\'s son lifted the princess into the carriage. The faithful Henry climbed up behind, full of joy at his master\'s freedom. When they had gone a short distance, the prince heard a crack behind him, as if something had broken. He turned and cried: "Henry, the carriage is breaking!"',
        '"No, my lord, the carriage does not break. It is a band around my heart, which suffered such great pain when you were living in the well." Two more times something cracked on the way. The prince always thought the carriage was breaking, but it was only the bands springing from the faithful heart of his servant, because his master was free and happy.',
      ],
    },
    {
      title: 'Little Red Cap',
      text: [
        'Once upon a time there was a sweet little girl. Everyone who saw her loved her, but most of all her grandmother. She did not know what to give the child next. Once she gave her a little cap made of red velvet. It suited her so well that she would never wear anything else. So she was always called Little Red Cap.',
        'One day her mother said to her: "Come, Little Red Cap. Here is a piece of cake and a bottle of wine. Take them to your grandmother. She is sick and weak, and they will do her well. Mind your manners and give her a good day. Do not run off the path, or you may fall and break the bottle."',
        'Little Red Cap promised to obey her mother. The grandmother lived out in the wood, half an hour\'s walk from the village. As Little Red Cap entered the wood, a wolf came up to her. She did not know what a wicked animal he was, and was not afraid of him.',
        '"Good day, Little Red Cap," said the wolf. "Thank you kindly, wolf," answered she. "Where are you going so early?" "To my grandmother\'s," said she. "And what are you carrying under your apron?" "Cake and wine. Grandmother is sick and weak, and this will make her stronger."',
        '"Where does your grandmother live, Little Red Cap?" "A quarter of an hour further into the wood, under the three great oak trees. Her house stands below the nut-trees. You must know the place," said Little Red Cap.',
        'The wolf thought to himself: "What a tender young creature. What a nice plump mouthful. I must act cleverly, so that I may catch both her and her grandmother." Then he walked for a short time by the side of Little Red Cap, and said: "See, Little Red Cap, how pretty the flowers are all around us. Why do you not look about you? I believe you do not even hear how sweetly the birds are singing. Just look at all the beautiful things growing here."',
        'Little Red Cap raised her eyes, and when she saw the sunbeams dancing here and there through the trees, and the pretty flowers growing everywhere, she thought: "If I take grandmother a fresh nosegay, it will please her very much." So she ran from the path into the wood to look for flowers. And each time she picked one, she saw a still prettier one further off, and went deeper and deeper into the wood.',
        'But the wolf ran straight to the grandmother\'s house and knocked at the door. "Who is there?" "Little Red Cap," replied the wolf. "I am bringing you cake and wine. Open the door." "Lift the latch," called out the grandmother. "I am too weak to get up." The wolf lifted the latch, walked in, and without saying a word, he swallowed up the poor grandmother.',
        'Then he put on her clothes, dressed himself in her cap, laid himself in bed, and drew the curtains.',
        'Little Red Cap had been running about picking flowers. When she had gathered all she could carry, she remembered her grandmother and set out on the way to her. She was surprised to find the cottage-door standing open. She walked in and felt so strange that she thought: "How uncomfortable I feel today. At other times I like being with grandmother so much."',
        'She went to the bed and drew back the curtains. There lay her grandmother with her cap pulled far over her face, looking very strange. "Oh, grandmother, what big ears you have!" "The better to hear you with, my child." "Oh, grandmother, what big eyes you have!" "The better to see you with, my dear." "Oh, grandmother, what large hands you have!" "The better to hug you with." "But grandmother, what a terrible big mouth you have!" "The better to eat you with!"',
        'And scarcely had the wolf said this, than he sprang out of the bed and swallowed up poor Little Red Cap.',
        'When the wolf had satisfied his appetite, he lay down again in the bed, fell asleep, and began to snore very loud. A huntsman was just passing the house. He thought: "How loudly the old woman is snoring. I must see if something is wrong." He stepped inside, and there in the bed lay the wolf.',
        '"So I have found you at last, you old sinner," said the huntsman. "I have been looking for you a long time." He was about to aim his gun, when it occurred to him that the wolf might have swallowed the grandmother, and that she might still be saved.',
        'So he did not shoot, but took a pair of scissors and began to cut open the sleeping wolf\'s stomach. After a few snips, he saw the little red cap. After a few more, the little girl sprang out, crying: "Oh, how frightened I was! It was so dark inside the wolf\'s body." And then the old grandmother came out alive as well.',
        'Then Little Red Cap fetched some great stones, with which they filled the wolf\'s belly. When he awoke, he wanted to run away. But the stones were so heavy that he fell down at once and died.',
        'All three were happy. The huntsman took the wolf\'s skin. The grandmother ate the cake and drank the wine, and grew strong again. And Little Red Cap thought to herself: "As long as I live, I will never leave the path by myself, when mother has forbidden me to do so."',
      ],
    },
    {
      title: 'Hansel and Gretel',
      text: [
        'Hard by a great forest dwelt a poor wood-cutter with his wife and his two children. The boy was called Hansel and the girl Gretel. He had little enough to eat, and once, when a great famine came to the land, he could no longer provide even daily bread.',
        'One night, as he lay in bed thinking about his worries, he sighed and said to his wife: "What is to become of us? How are we to feed our poor children, when we have nothing left for ourselves?" "I will tell you what, husband," answered the wife. "Early tomorrow morning we will take the children out into the forest, where it is thickest. We will make them a fire, give each of them one more piece of bread, and then go to our work. They will not find their way home, and we shall be rid of them."',
        '"No, wife," said the man. "I will not do that. How can I bear to leave my children alone in the wood? The wild animals would soon come and tear them to pieces." "What a fool you are!" said she. "Then we must all four die of hunger. You may as well plane the planks for our coffins." She left him no peace until he agreed.',
        '"But I am very sorry for the poor children all the same," said the man. The two children had not been able to sleep for hunger, and had heard what their stepmother had said to their father. Gretel wept bitter tears, and said to Hansel: "Now all is over with us." "Be quiet, Gretel," said Hansel. "Do not be afraid. I will find a way to help us."',
        'When the old people had fallen asleep, Hansel got up, put on his little coat, opened the door below, and crept outside. The moon shone brightly, and the white pebbles which lay in front of the house glittered like real silver coins. Hansel bent down and put as many of them into his pocket as it would hold. Then he went back and said to Gretel: "Be comforted, dear little sister, and sleep in peace. God will not leave us."',
        'Early in the morning, before the sun was up, the wife came and woke the two children. "Get up, you lazy things. We are going into the forest to fetch wood." She gave each of them a piece of bread. "There is something for your dinner, but do not eat it before then, for you will get no more." Gretel carried the bread under her apron, because Hansel\'s pockets were full of stones.',
        'They all set out together on the way to the forest. When they had walked a short time, Hansel stood still and looked back at the house. He did this again and again. His father said: "Hansel, what are you looking at? Mind your walking." "Ah, father," said Hansel, "I am looking at my little white cat. It is sitting on the roof, wanting to say goodbye to me."',
        'When they had reached the middle of the forest, the father made a fire. The wife said: "Now, children, pile up some wood. We will make a fire, and when it is burnt out, you shall stay by it and rest. We are going into the forest to cut wood. In the evening, when we are done, we will come and fetch you."',
        'When it was noon, Gretel shared her bread with Hansel, who had spread his on the ground. Then they fell asleep. The evening came, but no one came to fetch the poor children. They did not awake until it was dark night. Hansel comforted his little sister: "Wait, Gretel, until the moon rises. Then we will see the pebbles I dropped. They will show us the way home."',
        'When the moon came, they set out. The whole night they walked, and at break of day they arrived at their father\'s house. They knocked at the door. When the woman opened it and saw that it was Hansel and Gretel, she said: "You naughty children. Why did you sleep so long in the forest? We thought you would never come back." But the father was glad, for it had cut him to the heart to leave them behind alone.',
        'Not long afterwards, there was once more great scarcity in every corner of the land. One night, the children heard the mother say to the father: "Everything is eaten again. We have only half a loaf of bread left. After that, all is over. The children must go. We will take them deeper into the forest, so that they shall not find their way out."',
        'This time, Hansel could not get out to collect pebbles. The door was locked. But he comforted his little sister: "Do not cry, Gretel. Sleep in peace. God will help us." Early in the morning, the woman came and took them out of their beds. Their piece of bread was given to them, but it was still smaller than the last time.',
        'On the way into the forest, Hansel crumbled the bread in his pocket, and often stood still and threw a crumb on the ground. When they reached the middle of the forest, a great fire was again made. "Now sit there, children," said the woman. "When you are tired, you may sleep a little. We are going into the forest to cut wood. In the evening we will come and fetch you."',
        'When it was noon, Gretel shared her bread with Hansel. Then they walked until evening. But when they wanted to look for the crumbs, they found none. The birds of the forest had come and picked them all up.',
        '"We will find the way," said Hansel. But they did not find it. They walked the whole night and the next day, from morning till evening, but they came out of the forest. They were very hungry, for they had nothing to eat but a few berries. At last, they were so tired that their legs would carry them no longer, and they lay down beneath a tree and fell asleep.',
        'On the third day, when they set out again, it was still not long before they saw a little snow-white bird sitting on a branch. It sang so delightfully that they stood still and listened. When it had finished its song, it spread its wings and flew away before them. They followed it until they reached a little house. The bird perched on the roof. When they came quite close, they saw that the little house was built of bread, roofed with cakes, and the windows were of clear sugar.',
        '"Now we will set to work," said Hansel, "and have a good meal. I will eat a piece of the roof. You, Gretel, can eat some of the window. It will taste sweet." Hansel reached up and broke off a piece of the roof, to see how it tasted. Gretel leaned against the window and nibbled at the panes.',
        'Then a gentle voice called from the room: "Nibble, nibble, little mouse. Who is nibbling at my little house?" The children answered: "The wind, the wind, the heaven-born wind." And they went on eating without disturbance.',
        'But suddenly the door opened, and a very, very old woman came creeping out, leaning on a crutch. Hansel and Gretel were so terribly frightened that they let fall what they had in their hands. But the old woman shook her head and said: "Ah, you dear children. Who has brought you here? Just come in and stay with me. No harm shall happen to you."',
        'She took them both by the hand and led them into her little house. A good meal of milk and pancakes with apples and nuts was set before them. When they had finished, two little white beds were prepared for them. They lay down in them, and thought they were in heaven.',
        'But the old woman had only pretended to be so kind. She was in reality a wicked witch, who lay in wait for children. She had built the little house of bread in order to entice them there. When a child fell into her power, she killed it, cooked it, and ate it. That was a feast day for the witch.',
        'Early in the morning, before the children were awake, she got up. When she saw them sleeping so sweetly, with their full red cheeks, she muttered: "That will be a dainty bite." She seized Hansel with her thin hand, carried him into a little stable, and shut him up behind a grated door. He might scream as much as he liked, it did him no good.',
        'Then she went to Gretel, shook her awake, and cried: "Get up, lazy thing. Fetch some water and cook something good for your brother. He is sitting outside in a stable, and must be made fat. When he is fat enough, I will eat him." Gretel began to weep bitterly, but she was forced to do what the wicked witch told her.',
        'The best food was cooked for poor Hansel, but Gretel got nothing but crayfish shells. Every morning the old woman crept to the little stable and called: "Hansel, stretch out your finger, so that I may feel whether you will soon be fat." But Hansel stretched out a little bone to her. The old woman had dim eyes and could not see. She thought it was Hansel\'s finger, and wondered why he grew no fatter.',
        'When four weeks had passed and Hansel still remained thin, the witch lost patience. "Hurry up, Gretel," she cried. "Fetch water. Whether Hansel is fat or thin, tomorrow I will kill him and cook him."',
        'Oh, how the poor little sister grieved, as she was forced to carry the water. The tears ran down her cheeks. "Dear God, help us," she cried. "If only the wild animals in the forest had eaten us, at least we would have died together."',
        '"Save your screaming," said the witch. "It will not help you at all." Early in the morning, Gretel had to go out and fill the great pot with water. "We will bake first," said the old woman. "I have heated the oven already, and kneaded the dough." She pushed poor Gretel out to the oven, from which the flames of fire were already darting. "Creep in," said the witch, "and see if it is hot enough. We will put the bread inside."',
        'But when Gretel was inside, the witch meant to close the oven, and bake her too, and then eat her as well. But Gretel saw what she had in mind, and said: "I do not know how to do that. How can I get in?" "Stupid goose," said the old woman. "The opening is big enough. See, I could get in myself." She put her head into the oven. Then Gretel gave her a push, so that she went far inside, shut the iron door, and drew the bolt.',
        'The witch began to howl, quite horribly. But Gretel ran away, and the wicked witch was miserably burnt to ashes.',
        'Gretel ran as fast as she could to the stable, opened the door, and cried: "Hansel, we are saved. The old witch is dead." The door flew open, and Hansel sprang out like a bird out of its cage. How happy they were, how they jumped about each other, and how they caressed and kissed each other!',
        'As they had nothing more to fear, they went into the witch\'s house. In every corner there stood chests of pearls and precious stones. "This is better than pebbles," said Hansel, filling his pockets. Gretel said: "I will take some home too," and filled her little apron.',
        '"But now," said Hansel, "let us go out of the witch\'s forest." When they had walked a few hours, they came to a great stretch of water. "We cannot get over," said Hansel. "I see no bridge at all." "And there is no ferry boat either," answered Gretel. "But a white duck is swimming there. If I ask her, she will carry us over." She called: "Little duck, little duck, do you see? Hansel and Gretel are waiting for thee."',
        'The little duck came to them, and Hansel sat himself on its white back. "Sit down, Gretel," said the little duck. The duck carried them both over the water. When they had crossed over and had walked a short time, the forest seemed to them more and more familiar. At last, they saw from afar their father\'s house.',
        'They began to run, rushed inside, and threw themselves around their father\'s neck. The man had not known one happy hour since he had left the children in the forest. The stepmother, however, was dead. They emptied their pockets and aprons, and the pearls and precious stones rolled about the floor.',
        'Now all their cares were at an end, and they lived together in perfect happiness. And when the tale is told, the story of Hansel and Gretel has grown old — but remember the lesson: in the darkest forest, clever children may still find their way home.',
      ],
    },
  ],
};

const AESOP = {
  title: "Aesop's Fables（选）",
  author: 'Aesop',
  chaptersRaw: [
    {
      title: 'The Wolf and the Lamb',
      text: [
        'A wolf, meeting with a lamb astray from the fold, resolved not to lay violent hands on him, but to find some plea to justify to the lamb the wolf\'s right to eat him.',
        'He thus addressed him: "Sirrah, last year you grossly insulted me." "Indeed," bleated the lamb in a mournful tone of voice, "I was not then born."',
        'Then said the wolf, "You feed in my pasture." "No, good sir," replied the lamb, "I have not yet tasted grass."',
        'Again said the wolf, "You drink of my well." "No," exclaimed the lamb, "I never yet drank water, for as yet my mother\'s milk is both food and drink to me."',
        'Upon which the wolf seized him and ate him up, saying, "Well! I won\'t remain supperless, even though you refute every one of my imputations."',
        'The tyrant will always find a pretext for his tyranny.',
      ],
    },
    {
      title: 'The Fox and the Grapes',
      text: [
        'A famished fox saw some clusters of ripe black grapes hanging from a trellised vine.',
        'She resorted to all her tricks to get at them, but wearied herself in vain, for she could not reach them.',
        'At last she turned away, hiding her disappointment and saying: "The grapes are sour, and not ripe as I thought."',
      ],
    },
    {
      title: 'The Tortoise and the Hare',
      text: [
        'A hare one day ridiculed the short feet and slow pace of the tortoise, who replied, laughing: "Though you be swift as the wind, I will beat you in a race."',
        'The hare, believing her assertion to be simply impossible, assented to the proposal; and they agreed that the fox should choose the course and fix the goal.',
        'On the day appointed for the race the two started together. The tortoise never for a moment stopped, but went on with a slow but steady pace straight to the end of the course.',
        'The hare, lying down by the wayside, fell fast asleep. At last waking up, and moving as fast as he could, he saw the tortoise had reached the goal, and was comfortably dozing after her fatigue.',
        'Slow but steady wins the race.',
      ],
    },
    {
      title: 'The Boy Who Cried Wolf',
      text: [
        'A shepherd-boy, who watched a flock of sheep near a village, brought out the villagers three or four times by crying out, "Wolf! Wolf!"',
        'When his neighbors came to help him, he laughed at them for their pains.',
        'The wolf, however, did truly come at last. The shepherd-boy, now really alarmed, shouted in an agony of terror: "Pray, do come and help me; the wolf is killing the sheep."',
        'But no one paid any heed to his cries, nor rendered any assistance. The wolf, having no cause of fear, at his leisure lacerated or destroyed the whole flock.',
        'There is no believing a liar, even when he speaks the truth.',
      ],
    },
    {
      title: 'The Ant and the Grasshopper',
      text: [
        'In a field one summer\'s day a grasshopper was hopping about, chirping and singing to its heart\'s content.',
        'An ant passed by, bearing along with great toil an ear of corn he was taking to the nest.',
        '"Why not come and chat with me," said the grasshopper, "instead of toiling and moiling in that way?"',
        '"I am helping to lay up food for the winter," said the ant, "and recommend you to do the same."',
        '"Why bother about winter?" said the grasshopper; "we have got plenty of food at present."',
        'But the ant went on its way and continued its toil. When the winter came the grasshopper had no food and found itself dying of hunger, while it saw the ants distributing every day corn and grain from the stores they had collected in the summer.',
        'Then the grasshopper knew: it is best to prepare for the days of necessity.',
      ],
    },
    {
      title: 'The Lion and the Mouse',
      text: [
        'A lion was awakened from sleep by a mouse running over his face.',
        'Rising up angrily, he caught him and was about to kill him, when the mouse piteously entreated, saying: "If you would only spare my life, I would be sure to repay your kindness."',
        'The lion laughed and let him go.',
        'It happened shortly after this that the lion was caught by some hunters, who bound him by strong ropes to the ground.',
        'The mouse, recognizing his roar, came and gnawed the rope with his teeth, and set him free, exclaiming: "You ridiculed the idea of my ever being able to help you, expecting to receive from me any repayment of your favor; now you know that it is possible for even a mouse to confer benefits on a lion."',
      ],
    },
  ],
};

const MAGI = {
  title: 'The Gift of the Magi（节选简写）',
  author: 'O. Henry · 节选简写',
  chaptersRaw: [
    {
      title: 'One Dollar and Eighty-seven Cents',
      text: [
        'One dollar and eighty-seven cents. That was all. And sixty cents of it was in pennies. Pennies saved one and two at a time, by bargaining so hard with the grocer that her cheeks burned. Three times Della counted it. One dollar and eighty-seven cents. And the next day would be Christmas.',
        'There was clearly nothing left to do but flop down on the shabby little couch and howl. So Della did it. Which leads to the thought that life is made up of sobs, sniffles, and smiles — with sniffles predominating.',
        'While the mistress of the home is gradually subsiding from the first stage to the second, take a look at the home. A furnished flat at eight dollars per week. It did not exactly beggar description, but it certainly had that word on the way to look for it.',
        'Della finished her cry and attended to her cheeks with the powder rag. She stood by the window and looked out dully at a gray cat walking a gray fence in a gray backyard. Tomorrow would be Christmas Day, and she had only one dollar and eighty-seven cents with which to buy Jim a present.',
        'She had been saving every penny she could for months, with this result. Twenty dollars a week does not go far. Expenses had been greater than she calculated. They always are. Only one dollar and eighty-seven cents to buy a present for Jim. Her Jim. Many a happy hour she had spent planning for something nice for him. Something fine and rare and sterling — something just a little bit near to being worthy of the honor of being owned by Jim.',
        'There was a pier-glass between the windows of the room. Perhaps you have seen a pier-glass in an eight-dollar flat. A very thin and very agile person may, by observing his reflection in a rapid sequence of longitudinal strips, obtain a fairly accurate idea of his looks. Della, being slender, had mastered the art.',
        'Suddenly she whirled from the window and stood before the glass. Her eyes were shining brilliantly, but her face had lost its color within twenty seconds. Rapidly she pulled down her hair and let it fall to its full length.',
        'Now, the James Dillingham Youngs had two treasures of which they were mightily proud. One was Jim\'s gold watch that had been his father\'s and his grandfather\'s before him. The other was Della\'s hair. Had the Queen of Sheba lived in the flat across the airshaft, Della would have let her hair hang out the window some day to dry, just to depreciate Her Majesty\'s jewels and gifts. Had King Solomon been the janitor, with all his treasures piled up in the basement, Jim would have pulled out his watch every time he passed, just to see him pluck at his beard from envy.',
        'So now Della\'s beautiful hair fell about her, rippling and shining like a cascade of brown waters. It reached below her knee and made itself almost a garment for her. Then she put it up quickly, nervously, with a sudden motion. For a moment she stood still, with a little sob caught in her throat — and then, with a faint smile, she hurried out the door and down the stairs to the street.',
        'She stopped at a sign that read: "Mme. Sofronie. Hair Goods of All Kinds." Up she ran the flight of stairs, and stood panting before the shop. A large woman, too white for her trade, stood at the door.',
        '"Will you buy my hair?" asked Della.',
        '"I buy hair," said Madame. "Take your hat off and let us have a sight at the looks of it."',
        'Down rippled the brown cascade.',
        '"Twenty dollars," said Madame, lifting the mass with a practiced hand.',
        '"Give it to me quick," said Della.',
        'Oh, and the next two hours tripped by on rosy wings. She was ransacking the stores for Jim\'s present.',
        'She found it at last. It surely had been made for Jim and no one else. There was no other like it in any of the stores, and she had turned all of them inside out. It was a platinum fob chain, simple and chaste in design, properly proclaiming its value by substance alone and not by meretricious ornamentation. As soon as she saw it, she knew that it must be Jim\'s. It was like him. Quietness and value — the description applied to both. Twenty-one dollars they took from her for it. With that money left, she hurried home with the chain in her pocket, and the eighty-seven cents was all that remained.',
        'When Della reached home, her excitement gave way a little to prudence and reason. She got out her curling irons and lighted the gas and went to work repairing the ravages made by generosity added to love. Which is always a tremendous task, dear friends — a mammoth task.',
        'Within forty minutes her head was covered with tiny, close-lying curls that made her look wonderfully like a truant schoolboy. She looked at her reflection in the mirror long, carefully, and critically.',
        '"If Jim does not kill me," she said to herself, "before he takes a second look at me, he will say I look like a Coney Island chorus girl. But what could I do — oh! What could I do with a dollar and eighty-seven cents?"',
        'At seven o\'clock the coffee was made and the pan on the back of the stove was hot and ready to cook the chops. Jim was never late. Della doubled the little chain in her hand and sat on the corner of the table near the door that he always entered. Then she heard his step on the stair, and she turned white for just a moment. She had a habit of saying little silent prayers about the simplest things, and now she whispered: "Please God, make him think I am still pretty."',
        'The door opened and Jim stepped in and closed it. He looked thin and very serious. Poor fellow, he was only twenty-two — and to be burdened with a family! He needed a new overcoat and he was without gloves. Jim\'s eyes were fixed upon Della. There was an expression in them that she could not read, and it terrified her. It was not anger, nor surprise, nor disapproval, nor horror. He simply stared at her fixedly with that peculiar expression on his face.',
        'Della wriggled off the table and went to him.',
        '"Jim, darling," she cried, "do not look at me that way. I had my hair cut off and sold it. I could not have lived through Christmas without giving you a present. It will grow again — you will not mind, will you? My hair grows awfully fast. Say \'Merry Christmas!\' Jim, and let us be happy. You do not know what a nice — what a beautiful, nice gift I have got for you."',
        '"You have cut off your hair?" asked Jim, laboriously, as if he had not arrived at that fact clearly even after the hardest mental labor.',
        '"Cut it off and sold it," said Della. "Do you not like me just as well, anyhow? I am me without my hair, am I not?"',
        'Jim looked about the room curiously.',
        '"You say your hair is gone?" he said, with an air almost of idiocy.',
        '"You need not look for it," said Della. "It is sold, I tell you — sold and gone. It is Christmas Eve, boy. Be good to me, for it went for you. Maybe the hairs of my head were numbered," she went on with a sudden serious sweetness, "but nobody could ever count my love for you."',
        'Instead of obeying, Jim tumbled down on the couch and put his hands under the back of his head and smiled.',
        '"Dell," said he, "let us put our Christmas presents away and keep them a while. They are too nice to use just at present. I sold the watch to get the money to buy your combs. And now suppose you put the chops on."',
        'And here I have lamely related to you the uneventful chronicle of two foolish children in a flat who most unwisely sacrificed for each other the greatest treasures of their house. But in a last word to the wise of these days, let it be said that of all who give gifts, these two were the wisest. Everywhere they are wisest. They are the magi.',
      ],
    },
  ],
};

export const SAMPLES = [GRIMM, AESOP, MAGI];

// 向后兼容旧引用（单本示例书入口）
export const SAMPLE = AESOP;
